import Navbar from '../components/Navbar'
import Grid from '@mui/material/Grid'
import Head from 'next/head'

const Developer = ()=>{
    return (
        <>
            <Head>
                <title>Developer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            
                    <div style={{padding: '0 40px'}}>
                        <h3 style={{textAlign: 'center', marginBottom: '40px'}}>This App Was Developed Entirely By <b style={{fontSize: '1.2em', color: '#1976D2', cursor: 'pointer'}} onClick={()=>{window.open('https://www.linkedin.com/in/amer-sulaiman/')}}>Amer Sulaiman</b></h3>
                        <pre>
                            <p style={{fontSize: '1.2em', fontWeight: 'bold'}}>The Used Techstack:</p>
                            &nbsp;&nbsp;&nbsp;&nbsp;- React.js/Next.js (frontend) <br />
                            &nbsp;&nbsp;&nbsp;&nbsp;- Node.js/Express.js (Backend and API)
                            &nbsp;&nbsp;&nbsp;&nbsp;- Redux/Redux Toolkit (State Management)
                            &nbsp;&nbsp;&nbsp;&nbsp;- MongoDB (Database)

                            <p style={{fontSize: '1.2em', fontWeight: 'bold', marginTop: "20px"}}>What Does this website do?</p>
                            &nbsp;&nbsp;&nbsp;&nbsp;You can signup to upload quotes you like the browse quotes uploaded by other users.
                        </pre>
                    </div>
                    
                    

                
            
        </>
    )
}

export default Developer;